<?php

function fearch_views_pre_render(&$view)
{
	
	if ($view->name == "knowledge_center" && user_is_logged_in())
	{
		$viewInput = strtolower($view->exposed_raw_input['combine_1']);

		if ($viewInput == "")
		{
			return;
		}
	
		$viewQuery = split(' ', $viewInput);
		$whereClause = "";
		$parameters = array();
		
		// 1=1 is a terrible and lazy hack
		$baseQuery = "SELECT * FROM fearch_article a WHERE 1=1 ";

		for ($i=0; $i < count($viewQuery); ++$i) 
		{
			if ($viewQuery[$i] != "") 
			{ 
				$whereClause .= "AND (SELECT count(*) FROM fearch_word_article_view WHERE aid = a.id AND word like :p" . (string)$i . ") > 0 ";
				$parameters[":p" . $i] = "%" . db_like($viewQuery[$i]) . "%";
			}
		}

		$whereClause .= ";";

		$result = db_query($baseQuery . $whereClause, $parameters)->fetchAll();
		$group = array();

		// Put everthing into an object for grouping purposes
		for ($i=0; $i < count($result); ++$i) 
		{
			// Set the group as dir
			$dir = split('/', $result[$i]->uri);
			$dir = str_replace('_', ' ', $dir[0]);

			if ($group[$dir])
			{
				if ($group[$dir]["count"] <= 10)
				{
					$group[$dir]["count"] += 1;
					$group[$dir]["content"] .= '<div class="views-row kc-item">
						<span class="views-field views-field-title">
							<strong class="field-content">
								<a href="' . $result[$i]->uri . '" target="_blank">' . $result[$i]->name . '</a>
							</strong> 
						</span>
						<div class="views-field views-field-body">
							<span class="field-content">
								' . $result[$i]->preview . '
							</span>
						</div>
					</div>';
				}
				else
				{
					// More than 10 results returned
					$group[$dir]["more"] = true;
				}
			}
			else
			{
				$group[$dir]["content"] = '<div class="views-row kc-item">
						<span class="views-field views-field-title">
							<strong class="field-content">
								<a href="' . $result[$i]->uri . '" target="_blank">' . $result[$i]->name . '</a>
							</strong> 
						</span>
						<div class="views-field views-field-body">
							<span class="field-content">
								' . $result[$i]->preview . '
							</span>
						</div>
					</div>';
				$group[$dir]["count"] = 1;
			}
		}

		$attachment = "";

		foreach ($group as $key => $value) 
		{
			$attachment .= "<p> <h1>" . $key . "</p> </h1> <br> " . $value["content"] . ($value["more"] ? "<br> <p> Set limited to 10 results. Include more specific search terms for more accurate results.</p>" : "");
		}

		$view->attachment_after = $attachment;
	}
}
