<?php

function fearch_views_pre_render(&$view)
{
	$query = $view->exposed_raw_input->combine_1;

	//if ($query != "")
	//{
		$html = file_get_contents("https://127.0.0.1/sites/all/modules/daisey/files/rnotes/index.htm#search-" . $query);
		
		$xml = new SimpleXMLElement($html);
		$xpath = $xml->xpath('ul[@id="resultList"]');

		$view->attachment_before = "Query: " . $query;
		$view->attachment_after = "this is text " . $html;
	//}
}